version: "3.7"

volumes:
    prometheus_data:
    grafana_data: 


services:
  shuup:
    build:
      context: .
    ports:
      - "8016:8000"
    tty: true
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always  

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - shuup:shuup
    depends_on:
      - shuup
    restart: always
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    environment:
      - SMTP_PASSWORD
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    restart: always
  node_exporter:
    image: prom/node-exporter
    ports:
    - "9100:9100"
    restart: unless-stopped



